server:
  port: 8080

spring:
  application:
    name: kotlin-spring-boot-oauth-poc
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
