server:
  port: 8080

spring:
  application:
    name: kotlin-spring-boot-oauth-poc
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true

security:
  access_token:
    validity_period: 3600
  key_resource: jwt.jks
  key_pass: jkspass
  key_alias: jwttest
  resource_id: kotlin-spring-boot-oauth-poc
