INSERT INTO T_USER(LOGIN, PASSWORD) VALUES ('USER', '1234');

INSERT INTO T_CLIENT(LOGIN, PASSWORD, SCOPE, AUTHORIZED_GRANT_TYPES) VALUES ('CLIENT', '1234', 'POC', 'password,refresh_token');

COMMIT;
